### ISSUE TITLE
AttributeError: 'BlockManager' object has no attribute 'blknos'

### ISSUE THREAD

**Issue by neversettle-tech** [Sentient07/HeadHunter#20]
When running the evaluation code, an error is reported， 
AttributeError: 'BlockManager' object has no attribute 'blknos'

**Comment by Sentient07** [comment]
Please post the full traceback. It's nearly impossible to debug with just a single line of error message

**Comment by neversettle-tech** [comment]
![Uploading F5456A67-EFFD-4E18-AF5D-5704B47B2444.jpeg…]()

**Comment by neversettle-tech** [comment]
WARNING    [brambox.stat._matchboxes] Annotation and detection dataframes do not have the same image categories
Traceback (most recent call last):
  File "train.py", line 195, in <module>
    train()
  File "train.py", line 183, in train
    result_dict = evaluate(model, val_data_loader, benchmark=benchmark)
  File "/media/ubuntu/seu219/AnacondaCache/envs/env_super/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/ubuntu/seu219/handsomeShuai/highDense/headCounter/HeadHunter-master/head_detection/vision/engine.py", line 207, in evaluate
    pr_ = pr(pred_df, gt_df,  ignore=True)
  File "/media/ubuntu/seu219/AnacondaCache/envs/env_super/lib/python3.8/site-packages/brambox/stat/_pr.py", line 64, in pr
    det = match_det(det, anno, threshold, criteria=crit, class_label=label, ignore=2 if ignore else 0)
  File "brambox/stat/_matchboxes.pyx", line 195, in brambox.stat._matchboxes.match_det
  File "/media/ubuntu/seu219/AnacondaCache/envs/env_super/lib/python3.8/site-packages/brambox/util/_dualgroupby.py", line 52, in __init__
    self.df1 = {col: np_col(df1, col) for col in df1.columns}
  File "/media/ubuntu/seu219/AnacondaCache/envs/env_super/lib/python3.8/site-packages/brambox/util/_dualgroupby.py", line 52, in <dictcomp>
    self.df1 = {col: np_col(df1, col) for col in df1.columns}
  File "/media/ubuntu/seu219/AnacondaCache/envs/env_super/lib/python3.8/site-packages/brambox/util/_pd.py", line 147, in np_col
    return bm.blocks[bm.blknos[idx]].iget(bm.blklocs[idx])
AttributeError: 'BlockManager' object has no attribute 'blknos'

**Comment by Sentient07** [comment]
which benchmark are you trying on?

**Comment by neversettle-tech** [comment]
combined

**Comment by neversettle-tech** [comment]
Does this have anything to do with the benchmark?

**Comment by neversettle-tech** [comment]
At the same time, can you publish your pre-trained model
